services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: redaction_development
      MARIADB_PASSWORD: redaction
      MARIADB_ROOT_PASSWORD: redaction-root
      MARIADB_USER: redaction
    ports:
      - '3306:3306'
    volumes:
      - redaction-mariadb:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  redaction-mariadb:
