import { ApplicationError } from '../../../../../lib/errors/applicationError';
import { RawResponse } from '../../../../../lib/api/apiRouteCommon';
import { PartialInstance } from '../../../../../lib/db/types';
import Redaction, {
  RedactionAttributes,
} from '../../../../../lib/models/Redaction';
import { RedactionStatus } from '../../../../../lib/models/redactionTypes';
import { generateRedactedPDF } from '../../../../../lib/pdf/generateRedactedPDF';
import { getRedactionFile } from '../../../../../lib/storage/storageFunctions/redactionFile';
import { getUnreachableError } from '../../../../../lib/typescript/getUnreachableError';

/** Parameters for generating a PDF for one redaction document. */
export interface GenerateRedactedPDFForKeyRequest {
  key: string;
}

/**
 * Generate the current redacted PDF for download without persisting a copy.
 *
 * A document may be downloaded repeatedly as its enabled boxes change. The
 * source PDF stays private in storage, while the generated bytes are returned
 * directly to the caller. PDF generation does not change the initial
 * redaction-process status.
 */
export async function generateRedactedPDFForKey({
  key,
}: GenerateRedactedPDFForKeyRequest): Promise<RawResponse> {
  const redaction = (await Redaction.findOne({
    where: { key },
    attributes: ['status', 'redactionBoundingBoxes'],
  })) as PartialInstance<
    RedactionAttributes,
    'status' | 'redactionBoundingBoxes'
  > | null;

  if (!redaction) {
    throw new ApplicationError('We could not find this redaction.', 404);
  }

  switch (redaction.status) {
    case RedactionStatus.redacting:
      throw new ApplicationError(
        'This redaction is still being processed. Please try again later.',
        409
      );
    case RedactionStatus.error:
      throw new ApplicationError(
        'This redaction encountered an error and is not ready for download.',
        409
      );
    case RedactionStatus.redacted:
      break;
    default:
      throw getUnreachableError(redaction.status);
  }

  const pdf = await getRedactionFile(key);
  const response = await generateRedactedPDF({
    pdf,
    redactionBoundingBoxes: redaction.redactionBoundingBoxes,
  });

  const rawResponse: RawResponse = {
    contentType: 'application/pdf',
    response,
    additionalHeaders: {
      'Content-Disposition': 'attachment; filename="redacted.pdf"',
    },
  };
  return rawResponse;
}
