import { RawResponse } from '../../../../../lib/api/makeAPIRoute';
import {
  assertIsRedactedOrThrowApplicationError,
  findRedactionByKeyOrError,
} from '../../lib/findRedactionByKeyOrError';
import { generateRedactedPDF } from '../../../../../lib/pdf/generateRedactedPDF';
import { getRedactionFile } from '../../../../../lib/storage/storageFunctions/redactionFile';

/** Parameters for generating a PDF for one redaction document. */
export interface GenerateRedactedPDFForKeyRequest {
  key: string;
}

/**
 * Generate the current redacted PDF for download without persisting a copy.
 *
 * A document may be downloaded repeatedly as its enabled boxes change. The
 * source PDF stays private in storage, while the generated bytes are returned
 * directly to the caller. PDF generation does not change the initial
 * redaction-process status.
 */
export async function generateRedactedPDFForKey({
  key,
}: GenerateRedactedPDFForKeyRequest): Promise<RawResponse> {
  const redaction = await findRedactionByKeyOrError({
    key,
    attributes: ['status', 'redactionBoundingBoxes'],
  });
  assertIsRedactedOrThrowApplicationError(redaction);

  const pdf = await getRedactionFile(key);
  const response = await generateRedactedPDF({
    pdf,
    redactionBoundingBoxes: redaction.redactionBoundingBoxes,
  });

  const rawResponse: RawResponse = {
    contentType: 'application/pdf',
    response,
    additionalHeaders: {
      'Content-Disposition': 'attachment; filename="redacted.pdf"',
    },
  };
  return rawResponse;
}
