import IRS1040Scenario2JSON from './IRS1040Scenario2.json';
import USPassportCardSpecimen from './USPassportCardSpecimen.json';
import type { SinglePageRedactionBoundingBox } from '../../../models/redactionTypes';

/**
 * Redaction boxes generated from the corresponding fixture images.
 *
 * The JSON files are generated by `index.test.ts`; the assertions here keep
 * their imported values in the page-less automatic-box shape used by the
 * single-page vision function.
 */
export const TestRedactionBoundingBoxes = {
  irs1040Scenario2: IRS1040Scenario2JSON as SinglePageRedactionBoundingBox[],
  usPassportCardSpecimen:
    USPassportCardSpecimen as SinglePageRedactionBoundingBox[],
};
